In [1]:
import sys
sys.path.append('C:/Users/DVOS/Documents/Github/cmglib/cmglib')

In [2]:
import pandas as pd
import numpy as np
from report import Report
from pathlib import Path

In [7]:
sr3_folder = '../cmglib/'
tpl = 'TemplateReport.tpl'
report = Report(tpl)
prices = np.array([283, 0, -38, -13])
tma = 0.08

files = []
npv = []

for sr3_file in Path(sr3_folder).rglob('*.sr3'):
    print(sr3_file.stem)
    files += [sr3_file.stem]
    code = report.run_report(sr3_file)
    report.read_rwo()
    npv_real = report.npv(tma, prices)
    print(f'O valor de npv é {npv_real}')
    npv.append(npv_real)
    # repor

WARNING:root:O arquivo OLYMPUS_BHP_noWC_1 já existe e não será sobrescrito.
WARNING:root:O arquivo OLYMPUS_BHP_noWC_30 já existe e não será sobrescrito.
WARNING:root:O arquivo OLYMPUS_BHP_RC_10 já existe e não será sobrescrito.

OLYMPUS_BHP_noWC_1
O valor de npv é 1117176396.174203
OLYMPUS_BHP_noWC_30
O valor de npv é 1531510115.232533
OLYMPUS_BHP_RC_10
O valor de npv é 1933347055.9745142

In [5]:
sr3_folder = '../cmglib/'
tpl = 'TemplateReport.tpl'
report = Report(tpl)
prices = np.array([283, 0, -38, -13])
tma = 0.08

files = []
npv = []

for sr3_file in Path(sr3_folder).rglob('*.sr3'):
    print(sr3_file.stem)
    files += [sr3_file.stem]
    code = report.run_report(sr3_file)
    report.read_rwo()
    npv_real = report.npv(tma, prices)
    print(f'O valor de npv é {npv_real}')
    npv.append(npv_real)
    # repor

WARNING:root:O arquivo OLYMPUS_BHP_noWC_1 já existe e não será sobrescrito.
WARNING:root:O arquivo OLYMPUS_BHP_noWC_30 já existe e não será sobrescrito.
WARNING:root:O arquivo OLYMPUS_BHP_RC_10 já existe e não será sobrescrito.

OLYMPUS_BHP_noWC_1
O valor de npv é 1106932526.9583206
OLYMPUS_BHP_noWC_30
O valor de npv é 1518120627.5355854
OLYMPUS_BHP_RC_10
O valor de npv é 1935391272.3413777

In [6]:
report.rwo

     time  oil_prod  gas_prod   water_prod  water_inj     cash_flow
0       0       0.0         0      0.00000        0.0  0.000000e+00
1      31  165347.0         0      7.91317    89272.3  4.563236e+07
2      60  116179.0         0      6.28462   104663.0  3.151780e+07
3      91  125039.0         0     14.32910   124035.0  3.377304e+07
4     121  122798.0         0     56.09420   126933.0  3.309957e+07
..    ...       ...       ...          ...        ...           ...
236  7183   22033.3         0  95822.10000   119433.0  1.041555e+06
237  7213   21208.8         0  92988.10000   115714.0  9.642606e+05
238  7244   21797.6         0  96354.70000   119711.0  9.509992e+05
239  7274   20984.0         0  93498.40000   115981.0  8.777798e+05
240  7305   21568.9         0  96876.80000   119986.0  8.628623e+05

[241 rows x 6 columns]

In [28]:
sr3_folder = r'C:\Users\DVOS\OneDrive - PETROBRAS\Documentos\Pessoais\Doutorado\Softwares\ReservoirsDATA\OLYMPUS\OLYMPUS\Results_HF\ALL_OPEN_BHP_noWC'
tpl = 'TemplateReport.tpl'
report = Report(tpl)
prices = np.array([283, 0, -38, -13])
tma = 0.08

files = []
npv = []

for sr3_file in Path(sr3_folder).rglob('*.sr3'):
    print(sr3_file.stem)
    files += [sr3_file.stem]
    code = report.run_report(sr3_file)
    report.read_rwo()
    npv_real = report.npv(tma, prices)
    print(f'O valor de npv é {npv_real}')
    npv.append(npv_real)
    # repor

OLYMPUS_BHP_noWC_1
O valor de npv é 1106932526.9583206
OLYMPUS_BHP_noWC_10
O valor de npv é 1604025969.8875341
OLYMPUS_BHP_noWC_11
O valor de npv é 1354873268.8719497
OLYMPUS_BHP_noWC_12
O valor de npv é 1399081760.5336957
OLYMPUS_BHP_noWC_13
O valor de npv é 1283325483.7455654
OLYMPUS_BHP_noWC_14
O valor de npv é 1381745661.884665
OLYMPUS_BHP_noWC_15
O valor de npv é 957473559.2600914
OLYMPUS_BHP_noWC_16
O valor de npv é 1247788343.7123067
OLYMPUS_BHP_noWC_17
O valor de npv é 1259763680.298112
OLYMPUS_BHP_noWC_18
O valor de npv é 1096717636.9757924
OLYMPUS_BHP_noWC_19
O valor de npv é 1445924137.5133994
OLYMPUS_BHP_noWC_2
O valor de npv é 1461817955.9637625
OLYMPUS_BHP_noWC_20
O valor de npv é 1699623956.7339447
OLYMPUS_BHP_noWC_21
O valor de npv é 1525600009.6384454
OLYMPUS_BHP_noWC_22
O valor de npv é 974417472.5289322
OLYMPUS_BHP_noWC_23
O valor de npv é 1451130981.5451705
OLYMPUS_BHP_noWC_24
O valor de npv é 1050672612.1993746
OLYMPUS_BHP_noWC_25
O valor de npv é 1291050784.3952637
OLYMPUS_BHP_noWC_26
O valor de npv é 992928338.3935143
OLYMPUS_BHP_noWC_27
O valor de npv é 1383226895.098096
OLYMPUS_BHP_noWC_28
O valor de npv é 1096917637.4929817
OLYMPUS_BHP_noWC_29
O valor de npv é 1435052987.7827644
OLYMPUS_BHP_noWC_3
O valor de npv é 1531783967.4432802
OLYMPUS_BHP_noWC_30
O valor de npv é 1518120627.5355854
OLYMPUS_BHP_noWC_31
O valor de npv é 1113521713.060624
OLYMPUS_BHP_noWC_32
O valor de npv é 1326940879.1698914
OLYMPUS_BHP_noWC_33
O valor de npv é 1288118556.24242
OLYMPUS_BHP_noWC_34
O valor de npv é 1368100152.2425938
OLYMPUS_BHP_noWC_35
O valor de npv é 1656690014.5122378
OLYMPUS_BHP_noWC_36
O valor de npv é 1312415588.8547366
OLYMPUS_BHP_noWC_37
O valor de npv é 1273769250.2930703
OLYMPUS_BHP_noWC_38
O valor de npv é 1379066042.2545235
OLYMPUS_BHP_noWC_39
O valor de npv é 1000948372.5955089
OLYMPUS_BHP_noWC_4
O valor de npv é 1036176173.124637
OLYMPUS_BHP_noWC_40
O valor de npv é 924681055.8042418
OLYMPUS_BHP_noWC_41
O valor de npv é 1266360564.5070734
OLYMPUS_BHP_noWC_42
O valor de npv é 1427575929.0222962
OLYMPUS_BHP_noWC_43
O valor de npv é 1341748305.9433587
OLYMPUS_BHP_noWC_44
O valor de npv é 1331184534.6238363
OLYMPUS_BHP_noWC_45
O valor de npv é 1304980459.0187721
OLYMPUS_BHP_noWC_46
O valor de npv é 1258908833.4436436
OLYMPUS_BHP_noWC_47
O valor de npv é 1518121562.015115
OLYMPUS_BHP_noWC_48
O valor de npv é 1214026365.3171635
OLYMPUS_BHP_noWC_49
O valor de npv é 1577335815.5657167
OLYMPUS_BHP_noWC_5
O valor de npv é 1173962457.9199698
OLYMPUS_BHP_noWC_50
O valor de npv é 1088073396.2597828
OLYMPUS_BHP_noWC_6
O valor de npv é 1038438547.6046335
OLYMPUS_BHP_noWC_7
O valor de npv é 1182319676.0867743
OLYMPUS_BHP_noWC_8
O valor de npv é 1288783481.9296637
OLYMPUS_BHP_noWC_9
O valor de npv é 1316192909.3924415

In [29]:
report.rwo

     time  oil_prod  gas_prod    water_prod  water_inj     cash_flow
0       0       0.0         0       0.00000        0.0  0.000000e+00
1      31  171872.0         0       9.35625    96593.3  4.738371e+07
2      60  130186.0         0       6.90583   113062.0  3.537257e+07
3      91  138981.0         0      26.68370   132962.0  3.760210e+07
4     121  134652.0         0      96.83960   135068.0  3.634695e+07
..    ...       ...       ...           ...        ...           ...
236  7183   23054.3         0  233430.00000   257854.0 -5.698075e+06
237  7213   22098.9         0  226146.00000   249604.0 -5.584411e+06
238  7244   22685.9         0  233974.00000   257995.0 -5.824837e+06
239  7274   21788.5         0  226656.00000   249739.0 -5.693390e+06
240  7305   22375.2         0  234431.00000   258134.0 -5.931938e+06

[241 rows x 6 columns]

In [30]:
data = dict(zip(files, npv))
df = pd.Series(data=data, index=files)

In [3]:
df.to_csv(r"C:\Users\DVOS\OneDrive - PETROBRAS\Documentos\Pessoais\Doutorado\Softwares\ReservoirsDATA\OLYMPUS\OLYMPUS\Results_HF\RC_BHP_with_WC\npv_results_RC.csv")

NameError: name 'df' is not defined

In [33]:
df.describe()

count    5.000000e+01
mean     1.291169e+09
std      1.912057e+08
min      9.246811e+08
25%      1.128632e+09
50%      1.298016e+09
75%      1.420452e+09
max      1.699624e+09
dtype: float64

In [27]:
npv[-1]

1615170381.7060425

In [4]:
rc = pd.read_csv(r"C:\Users\DVOS\OneDrive - PETROBRAS\Documentos\Pessoais\Doutorado\Softwares\ReservoirsDATA\OLYMPUS\OLYMPUS\Results_HF\RC_BHP_with_WC\npv_results_RC.csv")

In [11]:
rc.describe()

                npv
count  5.000000e+01
mean   1.489577e+09
std    2.252611e+08
min    9.859609e+08
25%    1.324884e+09
50%    1.515810e+09
75%    1.638816e+09
max    1.935391e+09

In [12]:
rc.sort_values(by=['npv'])

                files           npv
34  OLYMPUS_BHP_RC_40  9.859609e+08
18  OLYMPUS_BHP_RC_26  1.008381e+09
33   OLYMPUS_BHP_RC_4  1.119813e+09
20  OLYMPUS_BHP_RC_28  1.194734e+09
14  OLYMPUS_BHP_RC_22  1.198794e+09
44   OLYMPUS_BHP_RC_5  1.227521e+09
0    OLYMPUS_BHP_RC_1  1.255494e+09
47   OLYMPUS_BHP_RC_7  1.256569e+09
32  OLYMPUS_BHP_RC_39  1.277155e+09
42  OLYMPUS_BHP_RC_48  1.287612e+09
35  OLYMPUS_BHP_RC_41  1.302858e+09
24  OLYMPUS_BHP_RC_31  1.303658e+09
7   OLYMPUS_BHP_RC_16  1.316952e+09
6   OLYMPUS_BHP_RC_15  1.348680e+09
45  OLYMPUS_BHP_RC_50  1.349816e+09
9   OLYMPUS_BHP_RC_18  1.365250e+09
48   OLYMPUS_BHP_RC_8  1.368998e+09
39  OLYMPUS_BHP_RC_45  1.369365e+09
17  OLYMPUS_BHP_RC_25  1.402866e+09
19  OLYMPUS_BHP_RC_27  1.416941e+09
46   OLYMPUS_BHP_RC_6  1.428578e+09
16  OLYMPUS_BHP_RC_24  1.434976e+09
40  OLYMPUS_BHP_RC_46  1.468031e+09
30  OLYMPUS_BHP_RC_37  1.487280e+09
38  OLYMPUS_BHP_RC_44  1.507298e+09
25  OLYMPUS_BHP_RC_32  1.524323e+09
5   OLYMPUS_BHP_RC_14  1.529045e+09
29  OLYMPUS_BHP_RC_36  1.536044e+09
15  OLYMPUS_BHP_RC_23  1.541333e+09
2   OLYMPUS_BHP_RC_11  1.558118e+09
13  OLYMPUS_BHP_RC_21  1.566455e+09
36  OLYMPUS_BHP_RC_42  1.578186e+09
37  OLYMPUS_BHP_RC_43  1.602898e+09
10  OLYMPUS_BHP_RC_19  1.608306e+09
21  OLYMPUS_BHP_RC_29  1.611382e+09
49   OLYMPUS_BHP_RC_9  1.615170e+09
11   OLYMPUS_BHP_RC_2  1.623507e+09
31  OLYMPUS_BHP_RC_38  1.643919e+09
27  OLYMPUS_BHP_RC_34  1.644875e+09
3   OLYMPUS_BHP_RC_12  1.647111e+09
8   OLYMPUS_BHP_RC_17  1.658063e+09
4   OLYMPUS_BHP_RC_13  1.659842e+09
41  OLYMPUS_BHP_RC_47  1.689195e+09
26  OLYMPUS_BHP_RC_33  1.714837e+09
23  OLYMPUS_BHP_RC_30  1.764889e+09
28  OLYMPUS_BHP_RC_35  1.865247e+09
22   OLYMPUS_BHP_RC_3  1.875879e+09
43  OLYMPUS_BHP_RC_49  1.879641e+09
12  OLYMPUS_BHP_RC_20  1.921611e+09
1   OLYMPUS_BHP_RC_10  1.935391e+09

# Percentile_Olympus

P50 = Realizacao_44

In [19]:
rc.npv.quantile(0.5, interpolation='nearest')

1507297701.212191

In [20]:
rc.loc[38, :]

files    OLYMPUS_BHP_RC_44
npv      1507297701.212191
Name: 38, dtype: object